language: node_js
sudo: required
node_js:
    - "4.0"
    
# install Java 8 as required by vnu.jar
before_install:
 - sudo apt-get update
 - sudo apt-get install oracle-java8-installer
 - sudo update-java-alternatives -s java-8-oracle

install:
    - npm install -g firebase-tools
    - pip install --user html5validator
    
script:
    - html5validator --root website/

after_success:
    - cd website
    - firebase deploy --token $FIREBASE_TOKEN
